name: "CI"
on:
  push:
    tags-ignore:
      - "**"
    branches:
      - "**"

jobs:
  ci:
    name: Run CI
    runs-on: ubuntu-20.04
    if: "!contains(github.event.head_commit.message, '[skip ci]') && !contains(github.event.head_commit.message, '[skip all]')"
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
      - name: Restore package dependencies from cache
        id: cache
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ hashFiles('package-lock.json') }}
      - name: Install missing dependencies
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install
      - name: Run tests
        run: npm test
      - name: Publish to NPM
        if: endsWith(github.ref, 'master')
        id: publish
        uses: JS-DevTools/npm-publish@v1
        with:
          token: ${{ secrets.NPM_TOKEN }}
      - name: Build TypeDoc
        if: "(steps.publish.outputs.type != 'none' || contains(github.event.head_commit.message, '[force typedoc]')) && endsWith(github.ref, 'master')"
        run: npx typedoc --mode file --theme minimal --excludePrivate --exclude "**/*.test.ts"
      - name: Deploy TypeDoc to GitHub Pages
        if: steps.publish.outputs.type != 'none'
        uses: JamesIves/github-pages-deploy-action@3.7.1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages
          FOLDER: docs
          CLEAN: true
